heat_template_version: '2016-10-14'

description: >
  Template for a windows host for malware analysis
  Version: 27FEB18

parameters:
  inst_name:
    type: string
    default: win_malware
  flavor:
    type: string
    default: cy.large
  image:
    type: string
    default: "Windows 10 - New"
  username:
    type: string
    default: user
  password:
    type: string
    hidden: true
    default: pass

resources:
  router1:
    type: OS::Neutron::Router
    properties:
      name: router1
      external_gateway_info:
        network: public

  router1_interface:
    type: OS::Neutron::RouterInterface
    properties:
      router: { get_resource: router1 }
      subnet: { get_resource: subnet1 }

  network1:
    type: OS::Neutron::Net
    properties:
      name: network1
      port_security_enabled: false

  subnet1:
    type: OS::Neutron::Subnet
    properties:
      cidr: 192.168.10.0/24
      network: { get_resource: network1 }
      name: subnet1
      dns_nameservers: [ "10.50.255.254" ]
      gateway_ip: 192.168.10.1

  host_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_resource: network1 }
      port_security_enabled: false

  host:
    type: OS::Nova::Server
    properties:
      name: { get_param: inst_name }
      image: { get_param: image }
      flavor: { get_param: flavor }
      networks: 
        - port: { get_resource: host_port }
      user_data_format: RAW
      user_data: { get_resource: host_config }

  host_config:
    type: OS::Heat::SoftwareConfig
    properties:
      config:
        str_replace:
          template: |
            #ps1_sysnative
            $ErrorActionPreference = 'SilentlyContinue'
            netsh advfirewall set allprofiles state off
            set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
            set-ItemProperty -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System' -name "dontdisplaylastusername" -Value 1
            (new-object System.net.WebClient).DownloadFile("https://download.mozilla.org/?product=firefox-latest-ssl&os=win64&lang=en-US","C:\firefox.exe")
            & c:\firefox.exe -ms
            # download the following files, IDA Free, Ollydbg, hex editor, regshot, sysinternals suite, wireshark, net connectivity emulation,
            # fake dns
            # python scripts from the pma book
            # make a script to download all the files from a local server
            net user /add $username $password /y
            net localgroup administrators /add $username
            exit 1001
          params:
            $username: { get_param: username }
            $password: { get_param: password }
